[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.30.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Redirect default Netlify subdomain to primary domain
https://flograttarola.netlify.com/* https://flograttarola.com/:splat 301!