[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.54"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirect]]
  from = "https://flograttarola.netlify.com/" #old path
  to = "https://flograttarola.com/" #new path
